# TCL File Generated by Component Editor 17.1
# Fri Mar 27 14:12:37 EDT 2020
# DO NOT MODIFY


# 
# SDRAM_Controller "SDRAM Controller" v1.0
#  2020.03.27.14:12:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module SDRAM_Controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME SDRAM_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MT3TB4_G-10
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "SDRAM Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SDRAM_Controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SDRAM_Controller.v VERILOG PATH SDRAM_Controller.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 read_n read_n Input 1
add_interface_port avalon_slave_0 byteenable_n byteenable_n Input 2
add_interface_port avalon_slave_0 address address Input 25
add_interface_port avalon_slave_0 write_data writedata Input 16
add_interface_port avalon_slave_0 read_data readdata Output 16
add_interface_port avalon_slave_0 wait_request waitrequest Output 1
add_interface_port avalon_slave_0 data_validation readdatavalid Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end DRAM_ADDR export Output 13


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock clock
set_interface_property conduit_end_1 associatedReset reset
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 DRAM_BA export Output 2


# 
# connection point conduit_end_2
# 
add_interface conduit_end_2 conduit end
set_interface_property conduit_end_2 associatedClock clock
set_interface_property conduit_end_2 associatedReset reset
set_interface_property conduit_end_2 ENABLED true
set_interface_property conduit_end_2 EXPORT_OF ""
set_interface_property conduit_end_2 PORT_NAME_MAP ""
set_interface_property conduit_end_2 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_2 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_2 DRAM_CAS_N export Output 1


# 
# connection point conduit_end_3
# 
add_interface conduit_end_3 conduit end
set_interface_property conduit_end_3 associatedClock clock
set_interface_property conduit_end_3 associatedReset reset
set_interface_property conduit_end_3 ENABLED true
set_interface_property conduit_end_3 EXPORT_OF ""
set_interface_property conduit_end_3 PORT_NAME_MAP ""
set_interface_property conduit_end_3 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_3 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_3 DRAM_CKE export Output 1


# 
# connection point conduit_end_4
# 
add_interface conduit_end_4 conduit end
set_interface_property conduit_end_4 associatedClock clock
set_interface_property conduit_end_4 associatedReset reset
set_interface_property conduit_end_4 ENABLED true
set_interface_property conduit_end_4 EXPORT_OF ""
set_interface_property conduit_end_4 PORT_NAME_MAP ""
set_interface_property conduit_end_4 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_4 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_4 DRAM_CS_N export Output 1


# 
# connection point conduit_end_5
# 
add_interface conduit_end_5 conduit end
set_interface_property conduit_end_5 associatedClock clock
set_interface_property conduit_end_5 associatedReset reset
set_interface_property conduit_end_5 ENABLED true
set_interface_property conduit_end_5 EXPORT_OF ""
set_interface_property conduit_end_5 PORT_NAME_MAP ""
set_interface_property conduit_end_5 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_5 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_5 DRAM_DQ export Bidir 16


# 
# connection point conduit_end_6
# 
add_interface conduit_end_6 conduit end
set_interface_property conduit_end_6 associatedClock clock
set_interface_property conduit_end_6 associatedReset reset
set_interface_property conduit_end_6 ENABLED true
set_interface_property conduit_end_6 EXPORT_OF ""
set_interface_property conduit_end_6 PORT_NAME_MAP ""
set_interface_property conduit_end_6 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_6 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_6 DRAM_LDQM export Output 1


# 
# connection point conduit_end_7
# 
add_interface conduit_end_7 conduit end
set_interface_property conduit_end_7 associatedClock clock
set_interface_property conduit_end_7 associatedReset reset
set_interface_property conduit_end_7 ENABLED true
set_interface_property conduit_end_7 EXPORT_OF ""
set_interface_property conduit_end_7 PORT_NAME_MAP ""
set_interface_property conduit_end_7 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_7 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_7 DRAM_RAS_N export Output 1


# 
# connection point conduit_end_8
# 
add_interface conduit_end_8 conduit end
set_interface_property conduit_end_8 associatedClock clock
set_interface_property conduit_end_8 associatedReset reset
set_interface_property conduit_end_8 ENABLED true
set_interface_property conduit_end_8 EXPORT_OF ""
set_interface_property conduit_end_8 PORT_NAME_MAP ""
set_interface_property conduit_end_8 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_8 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_8 DRAM_UDQM export Output 1


# 
# connection point conduit_end_9
# 
add_interface conduit_end_9 conduit end
set_interface_property conduit_end_9 associatedClock clock
set_interface_property conduit_end_9 associatedReset reset
set_interface_property conduit_end_9 ENABLED true
set_interface_property conduit_end_9 EXPORT_OF ""
set_interface_property conduit_end_9 PORT_NAME_MAP ""
set_interface_property conduit_end_9 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_9 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_9 DRAM_WE_N export Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1

